Repository gdsc-ssu/litera-sea-client, pull requests merged in 2024-02, with the labels that each got.

#2 [#1] feat: 헤더 완성
  package-lock.json
  package.json
  src/Router.tsx
  src/components/Header/Header.style.tsx
  src/components/Header/Header.tsx
  src/components/Layout/Layout.style.tsx
  src/components/Layout/Layout.tsx
  src/styles/colors.tsx
  tsconfig.json
  vite.config.ts
Labels: ✨ feat

#4 [#3] feat: 단계 요약 페이지 완성
  src/Router.tsx
  src/components/Button/BlueButton.tsx
  src/components/Button/Button.style.tsx
  src/components/Button/Button.tsx
  src/components/Button/NextButton.tsx
  src/components/Problem/Problem.tsx
  src/components/StateStage/StateStage.tsx
  src/components/Text/Text.tsx
  src/pages/ResultLoading/ResultLoading.tsx
  src/pages/Stage/Result/StageResult.tsx
  src/pages/Stage/StageCheck/Multiple.tsx
  src/pages/Stage/StageCheck/Vocabulary.tsx
  src/pages/StageCheck/StageCheck.tsx
  src/styles/colors.tsx
Labels: ✨ feat

#6 [#5] feat: 오늘의 요약 페이지
  src/Router.tsx
  src/components/AnswerInput/InputComponent.tsx
  src/components/PercentState/PercentState.tsx
  src/components/Problem/Problem.tsx
  src/pages/Stage/StageCheck/Multiple.tsx
  src/pages/Stage/StageCheck/Vocabulary.tsx
  src/pages/TodaySummary/Result.style.tsx
  src/pages/TodaySummary/SummaryResult.tsx
  src/pages/TodaySummary/TodaySummary.tsx
Labels: ✨ feat

#8 [#7] feat: 복습 페이지
  package-lock.json
  package.json
  src/Router.tsx
  src/components/List/ReviewList.tsx
  src/components/Problem/Problem.tsx
  src/components/Text/Text.tsx
  src/components/VocaModal/VocaModal.tsx
  src/pages/ReviewNote/ReviewNote.tsx
  src/pages/ReviewNote/Summary.tsx
Labels: ✨ feat

#14 [#13] feat: 메인 페이지
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/SVGs/BadgeIcon.svg
  src/assets/SVGs/BoatIcon.svg
  src/assets/SVGs/BoatSvg.svg
  src/assets/SVGs/IslandLockedSvg.svg
  src/assets/SVGs/IslandSvg.svg
  src/assets/SVGs/LevelIcon.svg
  src/assets/SVGs/LockSvg.svg
  src/assets/SVGs/NormalSvg.svg
  src/assets/SVGs/TodayIcon.svg
  src/assets/SVGs/UserHat.svg
  src/assets/SVGs/VocabookDeleteButton.svg
  src/assets/SVGs/VocabookSetting.svg
  src/components/Dashboard/Badge.tsx
  src/components/Dashboard/CurrentState.tsx
  src/components/Dashboard/Dashboard.tsx
  src/components/Dashboard/Report.tsx
  src/components/Header/Header.style.tsx
  src/components/Header/Header.tsx
  src/components/Map/Map.tsx
  src/components/Modals/ProfileModal.tsx
  src/pages/Main/Main.tsx
Labels: ✨ feat

#20 [#16] style: 지문에 스크롤 추가
  src/components/Text/Text.tsx
Labels: 💄 style

#23 [#22] feat: 메인 페이지 API 연결
  src/pages/Main/Main.tsx
  src/recoil/UserInfoAtom.tsx
Labels: ✨ feat

#26 [#25] feat: 404 페이지 처리
  .gitignore
  src/Router.tsx
  src/pages/404/NotFound.tsx
Labels: ✨ feat

#30 [#29] fix: axios instance API 주소 수정
  src/apis/axiosInstance.tsx
Labels: 🐛 fix

#35 [#32] feat: 헤더에 accessToken 권한 부여 및 오늘의 요약 GET api 연결
  src/Router.tsx
  src/apis/axiosInstance.tsx
  src/components/AnswerInput/InputComponent.tsx
  src/components/Button/NextButton.tsx
  src/components/StateStage/StateStage.tsx
  src/components/Text/Text.tsx
  src/pages/SignIn/SignIn.tsx
  src/pages/TodaySummary/TodaySummary.tsx
  src/recoil/SummaryAtom.tsx
Labels: ✨ feat

#38 [#36] feat: 메인 페이지 API 연결 완료
  src/apis/axiosInstance.tsx
  src/components/Map/Map.tsx
  src/pages/Main/Main.tsx
Labels: ✨ feat

#49 [#46] feat: word post api 완료
  src/apis/axiosInstance.tsx
  src/components/Text/Text.tsx
  src/components/VocaModal/VocaModal.tsx
Labels: ✨ feat

#44 [#24] feat: 단어장 페이지 API 연결
  src/components/Vocabook/WordCard.tsx
  src/components/Vocabook/WordContent.tsx
  src/pages/Vocabulary/Vocabulary.tsx
  src/pages/Vocabulary/VocabularyContents.tsx
  src/pages/Vocabulary/VocabularyStudy.tsx
Labels: ✨ feat

#50 [#43] 구글 로그인 구현
  package-lock.json
  package.json
  src/Router.tsx
  src/apis/axiosInstance.tsx
  src/assets/SVGs/GoogleLogo.svg
  src/components/Modals/NewVocabookModal.tsx
  src/components/Modals/ProfileModal.tsx
  src/pages/Main/Main.tsx
  src/pages/SignIn/SignIn.tsx
  src/pages/SignIn/SigningIn.tsx
  src/pages/SignOut/SignOut.tsx
Labels: ✨ feat
